name: ci

#worlflow def on(事件觸發流水線 放哪些事件會觸發)
#我們希望會推到這個分支一次我們就會觸發一次
#push: 代表當我們有push到這個分支的時候就會觸發
#pull_request: 代表當我們有pull request的時候就會觸發
#on下面塞要觸發的事件
#ci把新的code狀態整合到原本是好的狀態 做風格檢查 自動化means ci
#cd:c機器自動幫我們做這件事情；deploy建立好需要發布的東西，網站手動放到網頁sever上...

on: 
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 將 username 轉成小寫
        run: echo "LOWERCASE_USERNAME=${GITHUB_ACTOR@L}" >> "${GITHUB_ENV}"
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      
        #擴展更多跨版本的功能
        # name: Set up QEMU
        # uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6

        #latest 永遠指定最新的東西 沒有指定version
        with:
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_USERNAME }}/eqidv-back:latest
        
          